[problem]                           # ode problem
_name_ = "3body"
G = 1.0
m1 = 100.0
m2 = 1.0
m3 = 0.001

[algorithm]                         # data generation algorithm
# Available _name_ options and required keys:
#   "rhmc-H0"     : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "hmc-H0"      : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "trajensemble": epsilon, n_chains, n_trans_per_chain
#   "rhmc" / "hmc": beta, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection, [epsilon]
_name_ = "trajensemble"
epsilon = 0.01
n_chains = 4000
n_trans_per_chain = 50

[integration]
dt = 10.0                           # time interval 
nsteps = 1000                      # number of steps per interval
method = "KahanLi8"               # solver method
use_float64x4 = true               # use Float64x4 
