[problem]                           # ode problem
_name_ = "fpu"
omega = 300.0

[algorithm]                         # parareal algorithm
_name_ = "procrustes"
batch = true
with_additive = true
use_scaling = false
window_size = -1
k_most_recent = 1

[integration]
Delta_t = 1.0                       # time interval 
N = 500                              # number of intervals
Nf = 262144                         # number of fine steps per interval
Nc = 1                            # number of coarse steps per interval
niters = 1                         # number of parareal iterations
fine_method = "KahanLi8"            # fine solver method
coarse_method = "VelocityVerlet"        # coarse solver method
use_float64x4 = false               # use Float64x4 for coarse solver (fine solver always uses Float64x4)
nn_ckpt_path = "/workspace/projects_rui/learnsolnmap/deep_learning/logs/train/runs/20250406-182238_8x29ca/checkpoints/latest-epoch00499.ckpt"                   # nn checkpoint path
nn_model_name = "SFTaylorBasedT0CenteredSolutionMap"