#!/bin/bash 

PROBLEM=fpu
DELTAT=1e-0
NFINE=65536  # 2^16
#NFINE=64  # 2^6
METHOD=McAte5
DATADIR=../data/fpu/omega50/rhmc-H0/ma5_dt2.5e-1_h1.5259e-5_Nchains100_Njumps2000_sigma1e-1/ma5_Dt1e0_h1.5259e-5/
USE_FLOAT64X4=true

julia generate_targets.jl $PROBLEM $DELTAT $NFINE $METHOD $DATADIR/U0.csv $DATADIR/U1.csv $USE_FLOAT64X4 &&
julia generate_targets.jl $PROBLEM $DELTAT $NFINE $METHOD $DATADIR/U1.csv $DATADIR/U2.csv $USE_FLOAT64X4 &&
julia generate_targets.jl $PROBLEM $DELTAT $NFINE $METHOD $DATADIR/U2.csv $DATADIR/U3.csv $USE_FLOAT64X4 &&
julia generate_targets.jl $PROBLEM $DELTAT $NFINE $METHOD $DATADIR/U3.csv $DATADIR/U4.csv $USE_FLOAT64X4 &&
julia generate_targets.jl $PROBLEM $DELTAT $NFINE $METHOD $DATADIR/U4.csv $DATADIR/U5.csv $USE_FLOAT64X4
