[problem]                           # ode problem
_name_ = "alphaparticle"
epsilon = 0.05

[integration]
dt = 1e-2                       # time interval 
nsteps = 1                        # number of steps per interval
N = 1000000                              # number of intervals
method = "ImplicitMidpoint"            # solver method
adaptive = false                # adaptive time stepping
use_float64x4 = false               # use Float64x4
retfull = false             # return full history
