[problem]                           # ode problem
_name_ = "nco"
epsilon = 0.01

[algorithm]                         # data generation algorithm
# Available _name_ options and required keys:
#   "rhmc-H0"     : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "hmc-H0"      : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "trajensemble": epsilon, n_chains, n_trans_per_chain
#   "rhmc" / "hmc": beta, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection, [epsilon]
_name_ = "rhmc-H0"  
epsilon = 0.1
n_chains = 1000
n_trans_per_chain = 600
n_steps_per_trans = 1
with_rejection = false

[integration]
dt = 64.0                          # time interval 
nsteps = 1024                      # number of steps per interval
method = "KahanLi8"               # solver method
use_float64x4 = false               # use Float64x4 
