[problem]                           # ode problem
_name_ = "3body-2d"
G = 1.0
m1 = 1.0
m2 = 1.0
m3 = 1.0

[integration]
dt = 1e-3                       # time interval 
nsteps = 1                        # number of steps per interval
N = 10000                              # number of intervals
method = "DPRKN5"            # solver method
adaptive = true                # adaptive time stepping
use_float64x4 = true               # use Float64x4
retfull = false             # return full history
