i2h:
  _target_: torch.nn.Identity

h2h:
  _target_: networks.tiramisu.TiramisuNet
  in_features: 12 
  activation: 
    _target_: torch.nn.ELU
  expand_blocks: [5,5,5,5,5]
  shrink_blocks: [5,5,5,5,5] 
  bottleneck_layers: 5
  growth_rate: 32
  use_bn: False

h2o:
  _target_: torch.nn.Identity