_target_: datamodules.datamodules.DefaultDataModule

train:
  data_dir: ${paths.data_dir}/train
  sequence_len: 6
  dtype: float32
  downsample_factor: 1.

test:
  data_dir: ${paths.data_dir}/test
  sequence_len: 6
  dtype: float32
  downsample_factor: 1.

batch_size: 100
num_workers: 4
pin_memory: True