[problem]                           # ode problem
_name_ = "nco"
epsilon = 0.01

[algorithm]                         # parareal algorithm
_name_ = "sequential"

[integration]
Delta_t = 0.05                       # time interval 
N = 40000                              # number of intervals
Nf = 64                         # number of fine steps per interval
Nc = 1                            # number of coarse steps per interval
niters = 10                         # number of parareal iterations
fine_method = "KahanLi8"            # fine solver method
coarse_method = "CalvoSanz4"        # coarse solver method
# nn_ckpt_path =                    # nn checkpoint path
use_float64x4 = false               # use Float64x4 for coarse solver (fine solver always uses Float64x4)
