_target_: modules.solutionmap.BoostedSolutionMap

defaults:
  - problem: fpu
  - optimizer: adamw
  - scheduler: 1cycle
  - loss: energynormsquared
  - network: mlp
  - _self_

Delta_t: 1.0

regularization:
  comm_strength: 0.
  lagr_strength: 0.

weight_init: xavier_uniform

phi:
  module:
    _target_: modules.solutionmap.SolutionMap
  ckpt_path: ???

forward_type: simple
learn_residual: true
scaling_factor: 1e-2