_target_: modules.variable_timestep_taylor.TaylorBasedIdentityEnforcedSolutionMap

defaults:
  - problem: fpu
  - optimizer: adamw
  - scheduler: 1cycle
  - loss: energynormsquared
  - network: modmlp
  - _self_

order: 1

multiplier_activation:
  _target_: torch.nn.Tanh

loss_hparams: null
use_dimensionless: true

weight_init: xavier_uniform