_target_: modules.var_dt_solnmap.VariableDtSolutionMap

defaults:
  - problem: fpu
  - optimizer: adamw
  - scheduler: 1cycle
  - loss: energynormsquared
  - network: mlp
  - _self_

weight_init: xavier_uniform

loss_hparams: