#!/bin/bash

#SBATCH -N 1                    # Total number of nodes requested 
#SBATCH -n 48                   # Total number of cores requested 
#SBATCH -o logs/job.%j.out      # Name of stdout file (%j expands to jobId)
#SBATCH -e logs/err.%j.out      # Name of stderr file (%j expands to jobId)
#SCATCH -J parareal             # Job name
#SBATCH -p v100                 # Submission queue
#SBATCH -A ML-Nav               # Project name (allocation)
#SBATCH -t 24:00:00             # Max run time 

#SBATCH --mail-user=rfang@utexas.edu    # Desired email address
#SBATCH --mail-type=begin               # Send email at job start 


PROBLEM=fpu
OMEGA=300.
T_INIT=0.
T_END=1000.
N=1000
N_FINE=262144
N_COARSE=512
N_ITERS=10
FINE_METHOD=KahanLi8
COARSE_METHOD=CalvoSanz4
WITH_ADDITIVE=true
NUM_WORKERS=50
OUTPUT_DIR=./temp/202308261948
NN_CHECKPOINT=/work/08170/rfang/maverick2/learnsolnmap/solutionmap/15xywl3k/checkpoints/epoch19995-val_loss7.553e-06.ckpt
USE_FLOAT64X4=false

module load python3

export PATH="$WORK/downloads/julia-1.8.2/bin:$PATH"

LD_LIBRARY_PATH="" julia run_sequential.jl $PROBLEM $T_INIT $T_END $N --Nf $N_FINE -f $FINE_METHOD --output_dir ${OUTPUT_DIR}/ref --use_float64x4 --fpu_omega $OMEGA &&
LD_LIBRARY_PATH="" julia run_plain.jl      $PROBLEM $T_INIT $T_END $N $N_ITERS --Nf $N_FINE --Nc $N_COARSE -f $FINE_METHOD -c $COARSE_METHOD --output_dir ${OUTPUT_DIR}/plain     --fpu_omega $OMEGA &&
LD_LIBRARY_PATH="" julia run_phasecorr.jl  $PROBLEM $T_INIT $T_END $N $N_ITERS --Nf $N_FINE --Nc $N_COARSE -f $FINE_METHOD -c $COARSE_METHOD --output_dir ${OUTPUT_DIR}/phasecorr --fpu_omega $OMEGA &&
LD_LIBRARY_PATH="" julia run_plain.jl      $PROBLEM $T_INIT $T_END $N $N_ITERS --Nf $N_FINE -f $FINE_METHOD --nn_checkpoint_path $NN_CHECKPOINT --output_dir ${OUTPUT_DIR}/plain_nn --fpu_omega $OMEGA &&
LD_LIBRARY_PATH="" julia run_phasecorr.jl  $PROBLEM $T_INIT $T_END $N $N_ITERS --Nf $N_FINE -f $FINE_METHOD --nn_checkpoint_path $NN_CHECKPOINT --output_dir ${OUTPUT_DIR}/phasecorr_nn --fpu_omega $OMEGA &&

wait
