[problem]                           # ode problem
_name_ = "fpu"
omega = 100.0

[algorithm]                         # data generation algorithm
# _name_ = "trajensemble"
# epsilon = 1e-1
# n_chains = 4000
# n_trans_per_chain = 50

# _name_ = "hmc-H0"  
# epsilon = 0.2
# n_chains = 400
# n_trans_per_chain = 500
# n_steps_per_trans = 1
# with_rejection = false

_name_ = "rhmc-H0"  
epsilon = 0.2
n_chains = 400
n_trans_per_chain = 500
n_steps_per_trans = 1
with_rejection = false

# _name_ = "hmc"
# beta = 1.0
# n_chains = 5
# n_trans_per_chain = 10
# n_steps_per_trans = 1
# with_rejection = true

[integration]
dt = 0.5                           # time interval 
nsteps = 4096                      # number of steps per interval
method = "KahanLi8"               # solver method
adaptive = false                   # adaptive time stepping
use_float64x4 = true               # use Float64x4 
