scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: ${module.optimizer.lr}
  total_steps: ???
  epochs: null
  steps_per_epoch: null
  anneal_strategy: cos
  cycle_momentum: False
  three_phase: False
  pct_start: 0.
extras:
  interval: step
