scheduler:
  _target_: schedulers.cyclic.CustomCyclicLR
  steps_per_cycle: ???
  mult_factor: 1.
  base_lr: 1e-5
  max_lr: ${module.optimizer.lr}
  scale_mode: cycle
  scale_fn_type: exponential
  scale_fn_factor: 0.9
  anneal_strategy: cos
  pct_start: 0.3
extras:
  interval: step
