scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    mode: min
    factor: 0.85
    min_lr: 1.0e-9
    patience: 5
    cooldown: 5
    verbose: True
extras:
    monitor: ${replace:"__metric__/valid"}
    interval: epoch
    frequency: 1