# @package _global_

# to execute this experiment run:
# python eval.py experiment_eval=nco_t0centered

defaults:
  - override /datamodule: default
  - override /trainer: gpu
  - override /callbacks: 
    - metrics_logger
    - hparams_updater

trainer:
  inference_mode: false  # to avoid the model derivatives to be zeroed out

module:
  _target_: modules.variable_timestep.T0CenteredSolutionMap

datamodule:
  train:
    data_dir: /workspace/projects_rui/learnsolnmap/data1/nco/epsilon=1e-2/version22/Dt=5e0/train
    sequence_len: 2
    downsample_factor: 0.2
    Dt: 5.0
    # Dt_range: [-4.0, 4.0]
    # exclude: false
  test:
    data_dir: /workspace/projects_rui/learnsolnmap/data1/nco/epsilon=1e-2/version22/Dt=5e0/test
    sequence_len: 2
    downsample_factor: 1.
    Dt: 5.0
    # Dt_range: [-20., 20.]
    # exclude: false
  batch_size: 1000

save_test_predictions: false 

predict: true
# predict_nsteps: [1000, 1000, 1000, 1250, 1700, 2000, 2500, 5000, 10000, 20000]
# predict_Dt: [10.2, 11., 10., 8.0, 6.0, 5.0, 4.0, 2.0, 1.0, 0.5]
# predict_nsteps: [2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000]
# predict_Dt: [3., 3.5, 4., 4.5, 5., 5.5,  6., 6.5, 7.]
# predict_nsteps: [2000, 2000, 2000, 2000]
# predict_Dt: [4.25, 4.75, 5.25, 5.75]
predict_nsteps: [2000, 1000]
predict_Dt: [8.0, 9.0]

callbacks:
  hparams_updater:

    # loss_hparams:
    #   misfit: 
    #     strength: 1.0
    #   additive_vv:
    #     strength: 1.0
    #     batch_size: 500
    #     integrator:
    #       method: VelocityVerlet
    #       stepsize: 0.1
    #       nsteps: 1
    #     t_dist:
    #       type: uniform
    #       min: -10.
    #       max: 10.
          # type: normal
          # mean: 0.
          # std: 30.


    metric_hparams:
      dynamics:
        t_dist:
          # type: uniform
          # min: -10.
          # max: 10.
          type: normal
          mean: 5.0
          std: 0.5
      commutative: 
        t_dist:
          # type: uniform
          # min: -10.
          # max: 10.
          type: normal
          mean: 5.0
          std: 0.5
        s_dist:
          # type: uniform
          # min: -10.
          # max: 10.
          type: normal
          mean: 5.0
          std: 0.5
      commutative_vv: 
        integrator:
          method: VelocityVerlet
          stepsize: 0.1
          nsteps: 1
        t_dist:
          # type: uniform
          # min: -10.
          # max: 10.
          type: normal
          mean: 5.0
          std: 0.5
      additive: 
        t_dist:
          type: uniform
          min: -5.
          max: 5.
        s_dist:
          type: uniform
          min: -5.
          max: 5.
      additive_vv:
        integrator:
          method: VelocityVerlet
          stepsize: 0.1
          nsteps: 1
        t_dist:
          # type: uniform
          # min: -10.
          # max: 10.
          type: normal
          mean: 5.0
          std: 0.5
      dyadic:
        t_dist:
          type: uniform
          min: -5.
          max: 5.
      reversibility:
        t_dist:
          type: uniform
          min: -10.
          max: 10.
