[problem]                           # ode problem
_name_ = "3body-2d"
G = 1.0
m1 = 1.0
m2 = 1.0
m3 = 1.0

[algorithm]                         # data generation algorithm
# Available _name_ options and required keys:
#   "rhmc-H0"     : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "hmc-H0"      : epsilon, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection
#   "trajensemble": epsilon, n_chains, n_trans_per_chain
#   "rhmc" / "hmc": beta, n_chains, n_trans_per_chain, n_steps_per_trans, with_rejection, [epsilon]
_name_ = "rhmc-H0"  
epsilon = 0.2
n_chains = 400
n_trans_per_chain = 100
n_steps_per_trans = 1
with_rejection = true

[integration]
dt = 0.4                           # time interval 
nsteps = 40                     # number of steps per interval
method = "DPRKN5"               # solver method
use_float64x4 = true               # use Float64x4
abstol = 1e-11
reltol = 1e-11
